<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="16337" started-at="2017-09-09T10:50:10Z" finished-at="2017-09-09T10:50:26Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="16337" started-at="2017-09-09T10:50:10Z" finished-at="2017-09-09T10:50:26Z">
      <class name="Com.Flo.Testclasses.Requirements.Login.Login">
        <test-method status="PASS" signature="tearup()[pri:0, instance:Com.Flo.Testclasses.Requirements.Login.Login@47c62251]" name="tearup" is-config="true" duration-ms="11893" started-at="2017-09-09T16:20:10Z" finished-at="2017-09-09T16:20:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearup -->
        <test-method status="FAIL" signature="LoginToApp()[pri:0, instance:Com.Flo.Testclasses.Requirements.Login.Login@47c62251]" name="LoginToApp" duration-ms="2811" started-at="2017-09-09T16:20:22Z" finished-at="2017-09-09T16:20:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Corporate Dashboard] but found [Crporate Dashboard]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Corporate Dashboard] but found [Crporate Dashboard]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at Com.Flo.Pages.corporate.Corpdashboardpage_Functions.verifydashboardpage(Corpdashboardpage_Functions.java:21)
	at Com.Flo.Testclasses.Requirements.Login.Login.LoginToApp(Login.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginToApp -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:Com.Flo.Testclasses.Requirements.Login.Login@47c62251]" name="teardown" is-config="true" duration-ms="1603" started-at="2017-09-09T16:20:25Z" finished-at="2017-09-09T16:20:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LoginToApp status=FAILURE method=Login.LoginToApp()[pri:0, instance:Com.Flo.Testclasses.Requirements.Login.Login@47c62251] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- Com.Flo.Testclasses.Requirements.Login.Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
